version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - kafka
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - KAFKA_BROKER=kafka:9092

  preprocessor:
    build:
      context: ./mqtt_data_preprocessor
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mqtt
      - kafka
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - KAFKA_BROKER=kafka:9092
      - MQTT_BROKER=mqtt

  db_interface:
    build:
      context: ./db_interface
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - kafka
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - KAFKA_BROKER=kafka:9092

  anomaly_detector:
    build:
      context: ./anomaly_detector
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  mqtt:
    image: eclipse-mosquitto:2.0.14
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  plc_simulator:
    build:
      context: ./plc_simulator
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
