version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8004:8004"
    depends_on:
      - mongodb
      - kafka
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - KAFKA_BROKER=kafka:9092
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  preprocessor:
    build:
      context: ./mqtt_data_preprocessor
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mqtt
      - kafka
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - KAFKA_BROKER=kafka:9092
      - MQTT_BROKER=mqtt

  db_interface:
    build:
      context: ./db_interface
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - kafka
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - KAFKA_BROKER=kafka:9092

  anomaly_detector:
    build:
      context: ./anomaly_detector
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  mqtt:
    image: eclipse-mosquitto:2.0.14
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_INTER_BROKER_PROTOCOL_VERSION: "3.5"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped
    depends_on:
      - zookeeper

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server localhost:9092 --list",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  plc_simulator:
    build:
      context: ./plc_simulator
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt

volumes:
  kafka_data:
    driver: local
