# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_server.proto\"+\n\rCreateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x0e\x43reateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\",\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\".\n\rUpdateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08newValue\x18\x02 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb7\x01\n\x0f\x44\x61tabaseService\x12)\n\x06\x43reate\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12)\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12)\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=21
  _globals['_CREATEREQUEST']._serialized_end=64
  _globals['_CREATERESPONSE']._serialized_start=66
  _globals['_CREATERESPONSE']._serialized_end=99
  _globals['_READREQUEST']._serialized_start=101
  _globals['_READREQUEST']._serialized_end=127
  _globals['_READRESPONSE']._serialized_start=129
  _globals['_READRESPONSE']._serialized_end=173
  _globals['_UPDATEREQUEST']._serialized_start=175
  _globals['_UPDATEREQUEST']._serialized_end=221
  _globals['_UPDATERESPONSE']._serialized_start=223
  _globals['_UPDATERESPONSE']._serialized_end=256
  _globals['_DELETEREQUEST']._serialized_start=258
  _globals['_DELETEREQUEST']._serialized_end=286
  _globals['_DELETERESPONSE']._serialized_start=288
  _globals['_DELETERESPONSE']._serialized_end=321
  _globals['_DATABASESERVICE']._serialized_start=324
  _globals['_DATABASESERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
