apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detector
  labels:
    io.kompose.service: anomaly-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: anomaly-detector
  template:
    metadata:
      labels:
        io.kompose.service: anomaly-detector
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:9092
          image: magusdev/anomaly-detector:latest
          name: anomaly-detector
          ports:
            - containerPort: 8006
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: model-volume
              mountPath: /app/models
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-storage
      restartPolicy: Always
