apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detector
  template:
    metadata:
      labels:
        app: anomaly-detector
    spec:
      containers:
        - name: anomaly-detector
          image: magusdev/anomaly-detector:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: plc_data
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
          ports:
            - containerPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector
spec:
  ports:
    - port: 8006
      targetPort: 8006
  selector:
    app: anomaly-detector
