apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Walid\kompose.exe convert -f docker-compose.yml -o k8s-manifests
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: anomaly-detector
  name: anomaly_detector
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8006
  selector:
    io.kompose.service: anomaly-detector
