apiVersion: v1
kind: Service
metadata:
  namespace: distributed-system
metadata:
  annotations:
    kompose.cmd: C:\Users\Walid\kompose.exe convert -o k8s-manifests
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: api-gateway

