apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Walid\kompose.exe convert -f docker-compose.yml -o k8s-manifests
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-interface
  name: db-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-interface
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Walid\kompose.exe convert -f docker-compose.yml -o k8s-manifests
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: db-interface
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: MONGO_URI
              value: mongodb://mongodb:27017/
          image: db-interface
          name: db-interface
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
