apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Oulu\Distributed Systems\tools\kompose.exe convert -o k8s-manifests
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: db-interface
  name: db-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-interface
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Oulu\Distributed Systems\tools\kompose.exe convert -o k8s-manifests
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/distributedsystems-default: "true"
        io.kompose.service: db-interface
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: MONGO_URI
              value: mongodb://mongodb:27017/
          image: db-interface
          imagePullPolicy: Never
          name: db-interface
          ports:
            - containerPort: 8003
              hostPort: 8003
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}

