apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-trainer
  labels:
    app: ml-model-trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model-trainer
  template:
    metadata:
      labels:
        app: ml-model-trainer
    spec:
      containers:
        - name: ml-model-trainer
          image: walid852/ml-model-trainer:latest  # Ensure this matches the image you pushed to Docker Hub
          ports:
            - containerPort: 8521  # Adjust the port if necessary
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/"
          readinessProbe:
            httpGet:
              path: /health
              port: 8521
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8521
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: ml-model-trainer
  labels:
    app: ml-model-trainer
spec:
  selector:
    app: ml-model-trainer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP