apiVersion: v1
kind: Service
metadata:
  namespace: distributed-system
metadata:
  annotations:
    kompose.cmd: C:\Users\Walid\kompose.exe convert -o k8s-manifests
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb

