apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Mohammad\Tools\Kompose\kompose.exe convert -o k8s-manifests
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Mohammad\Tools\Kompose\kompose.exe convert -o k8s-manifests
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt
    spec:
      containers:
        - image: eclipse-mosquitto:2.0.14
          name: mqtt
          ports:
            - containerPort: 1883
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mqtt-config-volume
      restartPolicy: Always
      volumes:
        - name: mqtt-config-volume
          configMap:
            name: mqtt-config
status: {}
