apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Walid\kompose.exe convert -f docker-compose.yml -o k8s-manifests
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Walid\kompose.exe convert -f docker-compose.yml -o k8s-manifests
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mqtt
    spec:
      containers:
        - image: eclipse-mosquitto:2.0.14
          name: mqtt
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mqtt-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: mqtt-cm0
          name: mqtt-cm0
