apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Mohammad\Tools\Kompose\kompose.exe convert -o k8s-manifests
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: plc-simulator
  name: plc-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plc-simulator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Mohammad\Tools\Kompose\kompose.exe convert -o k8s-manifests
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: plc-simulator
    spec:
      containers:
        - env:
            - name: MQTT_BROKER
              value: mqtt
          image: walid852/plc-simulator:latest
          name: plc-simulator
          resources: {}
      restartPolicy: Always
status: {}
