apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Walid\kompose.exe convert -o k8s-manifests
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: plc-simulator
  name: plc_simulator
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: plc-simulator
