apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Oulu\Distributed Systems\tools\kompose.exe convert -o k8s-manifests
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: preprocessor
  name: preprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: preprocessor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Oulu\Distributed Systems\tools\kompose.exe convert -o k8s-manifests
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/distributedsystems-default: "true"
        io.kompose.service: preprocessor
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: MONGO_URI
              value: mongodb://mongodb:27017/
            - name: MQTT_BROKER
              value: mqtt
          image: magusdev/preprocessor
          name: preprocessor
          ports:
            - containerPort: 8002
              hostPort: 8002
              protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always
status: {}




