apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Mohammad\Tools\Kompose\kompose.exe convert -o k8s-manifests
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: preprocessor
  name: preprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: preprocessor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Mohammad\Tools\Kompose\kompose.exe convert -o k8s-manifests
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: preprocessor
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: MONGO_URI
              value: mongodb://mongodb:27017/
            - name: MQTT_BROKER
              value: mqtt
          image: magusdev/preprocessor:latest
          name: preprocessor
          ports:
            - containerPort: 8002
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Always
status: {}
